<?php
$helper = $this->helper('Magento\Search\Helper\Data');
?>
<div class="ks-page-content-body ks-form-steps-progress-page">
    <div class="ks-form-steps-progress">
        <div class="ks-form-steps-progress-header">
            <h3>Create new product</h3>
            <div class="ks-description">Add new product to your store</div>
        </div>
        <div class="ks-form-steps-progress-body">
            <div class="progress">
                <div class="progress-bar progress-bar" role="progressbar" style="width: 25%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
            </div>

            <div class="ks-step-items">
                <a id="first-item" href="#" class="ks-step-item ks-completed">Product Name</a>
                <a id="second-item" href="#" class="ks-step-item">Description</a>
                <a id="third-item" href="#" class="ks-step-item">Upload Media</a>
                <a id="last-item" href="#" class="ks-step-item">Finished</a>
            </div>
        </div>
    </div>
    <div class="ks-form-steps-progress-wrapper">
        <div class="ks-form-steps-progress-content">
            <div class="ks-form-steps-progress-content-wrapper ks-scrollable">
                <div class="ks-scroll-wrapper">
                    <form id="form" class="ks-step">
                        <div class="form-group">
                            <label for="productname">Product Name <span class="text-danger">*</span></label>
                            <input type="text"
                                   name="product_name"
                                   value="<?= !empty($product['product_name']) ? $product['name'] : '';?>"
                                   class="form-control" id="productname" aria-describedby="productnameHelp" placeholder="Enter Product Name">
                            <small id="productnameHelp" class="form-text text-muted">Type your product name</small>
                        </div>
                        <div class="form-group">
                            <label for="category">Category <span class="text-danger">*</span></label>
                            <input type="text"
                                   name="category[]"
                                   value="<?= !empty($product['category']) ? $product['category'] : '';?>"
                                   class="form-control" id="category" aria-describedby="categoryHelp" placeholder="Enter Product Name">
                            <small id="categoryHelp" class="form-text text-muted">Select Category</small>
                        </div>
                        <!-- Description -->
                        <div class="form-group">
                            <label for="description">Description <span class="text-danger">*</span></label>
                            <textarea name="description"
                                      class="form-control" id="description" aria-describedby="descriptionHelp" placeholder="Type your product description"><?= !empty($product['description']) ? $product['description'] : '' ; ?></textarea>
                            <small id="descriptionHelp" class="form-text text-muted">Product Description</small>
                        </div>
                        <!-- Short Description -->
                        <div class="form-group">
                            <label for="short-description">Short Description <span class="text-danger"></span></label>
                            <textarea
                                   name="short_description"
                                   class="form-control" id="short-description" aria-describedby="shortDescriptionHelp" placeholder="Enter Product Name"><?= !empty($product['short_description']) ? $product['short_description'] : '' ; ?></textarea>
                            <small id="shortDescriptionHelp" class="form-text text-muted">Short description for your product</small>
                        </div>
                         <div class="form-group">
                            <label for="sku">SKU <span class="text-danger">*</span></label>
                            <input type="text"
                                   name="sku"
                                   value="<?= !empty($product['sku']) ? $product['sku'] : '';?>"
                                   class="form-control" id="sku" aria-describedby="skuHelp" placeholder="Enter Product SKU">
                            <small id="skuHelp" class="form-text text-muted">Type your product SKU</small>
                        </div>
                        <div class="form-group">
                            <label for="price">Price <span class="text-danger">*</span></label>
                            <input type="text"
                                   name="price"
                                   value="<?= !empty($product['price']) ? $product['price'] : '';?>"
                                   class="form-control" id="price" aria-describedby="priceHelp" placeholder="Enter Product Price">
                            <small id="priceHelp" class="form-text text-muted">Type your product Price</small>
                        </div>
                        <div class="form-group">
                            <label for="stock">Stock Quantity <span class="text-danger">*</span></label>
                            <input type="text"
                                   name="stock"
                                   value="<?= !empty($product['stock']) ? $product['stock'] : '';?>"
                                   class="form-control" id="stock" aria-describedby="priceHelp" placeholder="Enter Product Stock Quantity">
                            <small id="priceHelp" class="form-text text-muted">Type your product Stock Quantity</small>
                        </div>
                        <div class="form-group">
                            <label for="stock_availablity">Stock Availablity <span class="text-danger">*</span></label>
                            <select name="stock_availablity"
                                   class="form-control" id="stock_availablity" aria-describedby="stockAvailablity" >
                                   <option <?= !empty($product['stock_availablity']) ? 'selected' : '' ; ?> value="1">In Stock</option>
                                   <option <?= !empty($product['stock_availablity']) ? 'selected' : '' ; ?> value="2">Out Of Stock</option>
                               </select>
                            <small id="stockAvailablity" class="form-text text-muted">Select your product Stock Availablity Status</small>
                        </div>
                        <div class="form-group">
                            <label for="visibilty">Stock Visibilty <span class="text-danger">*</span></label>
                            <select name="visibilty"
                                   class="form-control" id="visibilty" aria-describedby="visibiltyHelp" >
                                   <option value="0">Please Select ...</option>
                                   <option <?= !empty($product['visibilty']) ? 'selected' : '' ; ?> value="1">Not Visible Individually</option>
                                   <option <?= !empty($product['visibilty']) ? 'selected' : '' ; ?> value="2">Catalog</option>
                                   <option <?= !empty($product['visibilty']) ? 'selected' : '' ; ?> value="2">Search</option>
                                   <option <?= !empty($product['visibilty']) ? 'selected' : '' ; ?> value="2">Catalog, Search</option>

                               </select>
                            <small id="visibiltyHelp" class="form-text text-muted">Select your product Stock Visibilty</small>
                        </div>
                        <div class="form-group">
                            <label for="weight">Weight</label>
                            <input type="text"
                                   name="weight"
                                   value="<?= !empty($product['weight']) ? $product['weight'] : '';?>"
                                   class="form-control" id="weight" aria-describedby="weightHelp" placeholder="Enter Product Weight or 0 for downloadable products">
                            <small id="weightHelp" class="form-text text-muted">Type your product weight or 0 for downloadable products</small>
                        </div>
                        <input type="text" name="category_id" hidden="hidden" value="0">
                    </form>
                </div>

            </div>
            <div class="ks-controls ks-flex-end">
                <button class="btn btn-primary-outline ks-light ks-previous">Back</button>
                <button class="btn btn-primary ks-next">Next Step</button>
            </div>
        </div>
    </div>
</div>
