<?php
$helper = $this->helper('Magento\Search\Helper\Data');

//Generate Form Key
$objectManager = \Magento\Framework\App\ObjectManager::getInstance(); 
$FormKey = $objectManager->get('Magento\Framework\Data\Form\FormKey');
$helper = $objectManager->get('AWstreams\Marketplace\Helper\Data');

?>
<div class="ks-page-content-body ks-form-steps-progress-page">
    <div class="ks-form-steps-progress">
        <div class="ks-form-steps-progress-header">
            <h3>Create new product</h3>
            <div class="ks-description">Add new product to your store</div>
        </div>
        <div class="ks-form-steps-progress-body">
            <div class="progress">
                <div class="progress-bar progress-bar" role="progressbar" style="width: 25%" aria-valuenow="33" aria-valuemin="0" aria-valuemax="100"></div>
            </div>

        </div>
    </div>
    <div class="ks-form-steps-progress-wrapper">
        <div class="ks-form-steps-progress-content" style="max-width:100%">
            <div class="ks-form-steps-progress-content-wrapper ks-scrollable">
                <div class="ks-scroll-wrapper">
                    <form id="form" method="post" action="<? echo $block->getPostActionUrl();?>" enctype="multipart/form-data" class="ks-step">
                        <input name="form_key" type="hidden" value="<?php echo $block->getFormKey();?>">
                        <div class="form-group row">
                            <label for="productname">Product Name <span class="text-danger">*</span></label>
                            <input type="text"
                                   name="product[name]"
                                   value="<?= !empty($product['name']) ? $product['name'] : '';?>"
                                   class="form-control" id="productname" aria-describedby="productnameHelp" placeholder="Enter Product Name">
                            <small id="productnameHelp" class="form-text text-muted">Type your product name</small>
                        </div>
                        <!--<div class="form-group row">
                            <label for="category">Category <span class="text-danger">*</span></label>
                            <input type="text"
                                   name="category[]"
                                   value="<?/*= !empty($product['category']) ? $product['category'] : '';*/?>"
                                   class="form-control" id="category" aria-describedby="categoryHelp" placeholder="Enter Product Name">
                            <small id="categoryHelp" class="form-text text-muted">Select Category</small>
                        </div>-->
                        <!-- Description -->
                        <div class="form-group row">
                            <label for="description">Description <span class="text-danger">*</span></label>
                            <textarea name="product[description]"
                                      class="form-control" id="description" aria-describedby="descriptionHelp" placeholder="Type your product description"><?= !empty($product['description']) ? $product['description'] : '' ; ?></textarea>
                            <small id="descriptionHelp" class="form-text text-muted">Product Description</small>
                        </div>
                        <!-- Short Description -->
                        <div class="form-group row">
                            <label for="short-description">Short Description <span class="text-danger"></span></label>
                            <textarea
                                   name="product[short_description]"
                                   class="form-control" id="short-description" aria-describedby="shortDescriptionHelp" placeholder="Enter Product Name"><?= !empty($product['short_description']) ? $product['short_description'] : '' ; ?></textarea>
                            <small id="shortDescriptionHelp" class="form-text text-muted">Short description for your product</small>
                        </div>
                         <div class="form-group row">
                            <label for="sku">SKU <span class="text-danger">*</span></label>
                            <input type="text"
                                   name="product[sku]"
                                   value="<?= !empty($product['sku']) ? $product['sku'] : '';?>"
                                   class="form-control" id="sku" aria-describedby="skuHelp" placeholder="Enter Product SKU">
                            <small id="skuHelp" class="form-text text-muted">Type your product SKU</small>
                        </div>
                        <div class="form-group row">
                            <label for="price">Price <span class="text-danger">*</span></label>
                            <input type="text"
                                   name="product[price]"
                                   value="<?= !empty($product['price']) ? $product['price'] : '';?>"
                                   class="form-control" id="price" aria-describedby="priceHelp" placeholder="Enter Product Price">
                            <small id="priceHelp" class="form-text text-muted">Type your product Price</small>
                        </div>
                        <div class="form-group row">
                            <label for="stock">Stock Quantity <span class="text-danger">*</span></label>
                            <input type="text"
                                   name="product[quantity_and_stock_status][qty]"
                                   value="<?= !empty($product['quantity_and_stock_status']['qty']) ? $product['quantity_and_stock_status']['qty'] : '1';?>"
                                   class="form-control" id="stock" aria-describedby="priceHelp" placeholder="Enter Product Stock Quantity">
                            <small id="priceHelp" class="form-text text-muted">Type your product Stock Quantity</small>
                        </div>
                        <div class="form-group row">
                            <label for="stock_availablity">Stock Availablity <span class="text-danger">*</span></label>
                            <select name="product[quantity_and_stock_status][is_in_stock]"
                                   class="form-control" id="stock_availablity" aria-describedby="stockAvailablity" >
                                   <option <?= (!empty($product['quantity_and_stock_status']['is_in_stock']) && $product['quantity_and_stock_status']['is_in_stock'] == 1 ) ? 'selected' : '' ; ?> value="1">In Stock</option>
                                   <option <?= (!empty($product['quantity_and_stock_status']['is_in_stock']) && $product['quantity_and_stock_status']['is_in_stock'] == 1 ) ? 'selected' : '' ; ?> value="0">Out Of Stock</option>
                               </select>
                            <small id="stockAvailablity" class="form-text text-muted">Select your product Stock Availablity Status</small>
                        </div>
                        <div class="form-group row">
                            <label for="visibilty">Stock Visibilty <span class="text-danger">*</span></label>
                            <select name="product[visibilty]"
                                   class="form-control" id="visibilty" aria-describedby="visibiltyHelp" >
                                   <option value="0">Please Select ...</option>
                                   <option <?= !empty($product['visibilty']) ? 'selected' : '' ; ?> value="1">Not Visible Individually</option>
                                   <option <?= !empty($product['visibilty']) ? 'selected' : '' ; ?> value="2">Catalog</option>
                                   <option <?= !empty($product['visibilty']) ? 'selected' : '' ; ?> value="3">Search</option>
                                   <option <?= !empty($product['visibilty']) ? 'selected' : '' ; ?> value="4">Catalog, Search</option>

                               </select>
                            <small id="visibiltyHelp" class="form-text text-muted">Select your product Stock Visibilty</small>
                        </div>
                        <div class="form-group row">
                            <label for="product_purchase_limit">Weight</label>
                            <input type="text"
                                   name="product[product_purchase_limit]"
                                   value="<?= !empty($product['product_purchase_limit']) ? $product['product_purchase_limit'] : '';?>"
                                   class="form-control" id="product_purchase_limit" aria-describedby="product_purchase_limitHelp" placeholder="Type Maximum number that  a single customer can purchase">
                            <small id="product_purchase_limitHelp" class="form-text text-muted">Type Maximum number that  a single customer can purchase</small>
                        </div>
                        <div class="form-group row">
                            <label for="weight">Product Purchase limit per customer</label>
                            <input type="text"
                                   name="product[weight]"
                                   value="<?= !empty($product['weight']) ? $product['weight'] : '';?>"
                                   class="form-control" id="weight" aria-describedby="weightHelp" placeholder="Enter Product Weight or 0 for downloadable products">
                            <small id="weightHelp" class="form-text text-muted">Type your product weight or 0 for downloadable products</small>
                        </div>
                      <div class="form-group row">
                            <div id="product-images" class="dropzone">
                            </div>
                        </div>
                        <div class="form-group row">
                            <label for="meta_title">Meta Title<span class="text-danger">*</span></label>
                            <input type="text"
                                   name="product[meta_title]"
                                   value="<?= !empty($product['meta_title']) ? $product['meta_title'] : '';?>"
                                   class="form-control" id="meta_title" aria-describedby="metaTitleHelp" placeholder="Enter Product Meta Title">
                            <small id="metaTitleHelp" class="form-text text-muted">Type your product meta title</small>
                        </div>
                        <div class="form-group row">
                            <label for="meta_keyword">Meta Keywords<span class="text-danger">*</span></label>
                            <input type="text"
                                   name="product[meta_keyword]"
                                   value="<?= !empty($product['meta_keyword']) ? $product['meta_keyword'] : '';?>"
                                   class="form-control" id="meta_keyword" aria-describedby="metaKeywordHelp" placeholder="Enter Product Meta Keywords">
                            <small id="metaKeywordHelp" class="form-text text-muted">Type your product meta keywords</small>
                        </div>
                        <!-- Description -->
                        <div class="form-group row">
                            <label for="meta_description">Meta Description <span class="text-danger">*</span></label>
                            <textarea name="product[meta_description]"
                                      class="form-control" id="meta_description" aria-describedby="metaDescriptionHelp" placeholder="Type your product meta description"><?= !empty($product['meta_description']) ? $product['meta_description'] : '' ; ?></textarea>
                            <small id="metaDescriptionHelp" class="form-text text-muted">Product MetaDescription</small>
                        </div>

                </div>

            </div>
            <div class="ks-controls ks-flex-end">
                <button class="btn btn-primary-outline ks-light ks-previous">Back</button>
                <button class="btn btn-primary ks-next">Next Step</button>
            </div>
             </form>

        </div>
    </div>
</div>
<script type="text/javascript">
    require(["jquery", "Dropzone"], function($) {


        $(document).ready(function () {
            var i = 0;
            new Dropzone('#product-images', {
                url: '<?=$block->getImageUploadAction();?>',
                init: function () {
                   var _this = this;
                    this.on("success", function (file, result) {
                        if(result.success == 200){
                            $('#product-images').append('<input id="image-'+i+'" type="text" name="image[]" value="' + result.path + '" hidden="hidden"/>');
                            $(".dz-remove").html("<div><span class='glyphicon glyphicon-trash' style='font-size: 1.5em'></span></div>");
                            var removeButton = Dropzone.createElement("<button data-id ='" + i + "' data-dz-remove " +
                                "class='del_thumbnail btn btn-default'><span class='glyphicon glyphicon-trash'></span></button>");
                            i++;
                            removeButton.addEventListener("click", function (e) {
                                e.preventDefault();
                                e.stopPropagation();

                                _this.removeFile(file);
                                $('#image-'+$(this).data('id')).remove();
                            });
                            file.previewElement.appendChild(removeButton);
                        }else{
                            var node, _i, _len, _ref, _results;
                            var message = response.msg // modify it to your error message
                            file.previewElement.classList.add("dz-error");
                            _ref = file.previewElement.querySelectorAll("[data-dz-errormessage]");
                            _results = [];
                            for (_i = 0, _len = _ref.length; _i < _len; _i++) {
                                node = _ref[_i];
                                _results.push(node.textContent = message);
                            }
                            return _results;
                        }
                    });

                },

            });

        });
    });
</script>