<?php

$data           = $block->getData1();
$data           = $data['landing_page_settings'];

//banner
$isBanner       = $data['display_banner'];
$bannerImage    = $this->getUrl()."pub/media/marketplace/".$data['banner_image'];
$bannerContent  = $data['banner_content'];

//icons
$label1         = $data['marketplace_landing_page_label1'];
$isIcons        = $data['display_icons'];

$icon1          = $this->getUrl()."pub/media/marketplace/".$data['feature1_icon'];
$iconLabel1     = $data['Feature1_icon_label'];

$icon2          = $this->getUrl()."pub/media/marketplace/".$data['feature2_icon'];
$iconLabel2     = $data['Feature2_icon_label'];

$icon3          = $this->getUrl()."pub/media/marketplace/".$data['feature3_icon'];
$iconLabel3     = $data['Feature3_icon_label'];

$icon4          = $this->getUrl()."pub/media/marketplace/".$data['feature4_icon'];
$iconLabel4     = $data['Feature4_icon_label'];


//products
$label2         = $data['marketplace_landing_page_label2'];
$label3         = $data['marketplace_landing_page_label3'];
$shops          = $block->getShops();
$countShops     = count($shops);
$cols           = 0 ;
//about
$label4         = $data['marketplace_landing_page_label4'];
$about          = $data['about_marketplace'];


switch ($countShops){
    case 1 : $cols = 4 ; break;
    case 2 : $cols = 6 ; break;
    case 3 : $cols = 4 ; break;
    case 4 : $cols = 3 ; break;
    default: $cols = 3 ; break;
}



?>

<!--banner-->
<? if($isBanner):?>
<div class="am-banner">
    <div class="row">
        <div class="col-md-12">
          <div class="cont text-center">
              <div class="image" style="background: url('<?= $bannerImage?>')" >
                  <h1>Open a Marketplace Shop</h1>
                  <p><?= $bannerContent ?></p>
                  <a href="<?= $block->getUrl(). 'customer/account/login/' ?>" class="btn btn-default">Open a Marketplace Shop</a>
              </div>
          </div>
        </div>
    </div>
</div>
<?endif;?>


<!--Icons-->
<? if($isIcons):?>
    <div class="am-icons text-center">
        <h1 class="text-center"><?= $label1 ?> </h1>
        <div class="row">
            <div class="col-md-3">
                <div class="cont ">
                    <img src="<?=$icon1 ?>" alt="">
                    <h4><?= $iconLabel1 ?></h4>
                </div>
            </div>
            <div class="col-md-3">
                <div class="cont ">
                    <img src="<?=$icon2 ?>" alt="">
                    <h4><?= $iconLabel2 ?></h4>
                </div>
            </div>
            <div class="col-md-3">
                <div class="cont ">
                    <img src="<?=$icon3 ?>" alt="">
                    <h4><?= $iconLabel3 ?></h4>
                </div>
            </div>
            <div class="col-md-3">
                <div class="cont ">
                    <img src="<?=$icon4 ?>" alt="">
                    <h4><?= $iconLabel4 ?></h4>
                </div>
            </div>
        </div>
    </div>
<?endif;?>

<hr>
<!--products-->
<div class="am-products">
    <h1 class="text-center"><?= $label2 ?> </h1>
    <div class="row">

        <?php
        $i = 0 ;
        foreach ($shops as $shop):
            $products = $block->getProducts($shop['customer_id']);
            ?>

            <div class="col-md-<?= $cols ?>">

                <div class="cont " style="height: 600px ;border: 1px solid #ccc;padding: 10px">
                    <div class="col1">
                        <div class="pull-left" style="width: 49%">
                            <a href="<?=$block->getUrl() . strtolower(str_replace(' ' ,'-' ,isset($products[0][0]) ? $products[0][0]: '#'  )).'.html'?>">
                                <?php if(!empty($products[0][1]))
                                echo "<img class='img-responsive img-thumbnail' style='width: 95%;height: 150px;'  src='" . $block->getUrl() . "pub/media/catalog/product" . $products[0][1] . "'>";
                                else
                                echo '<img class="img-responsive img-thumbnail" style="width: 95%;height: 150px;" src="'. $block->getUrl().'pub/static/version1512386094/frontend/Magento/luma/en_US/Magento_Catalog/images/product/placeholder/image.jpg">';
                                ?>
                            </a>
                        </div>

                        <div class="pull-left" style="width: 49%">
                            <a href="<?=$block->getUrl() . strtolower(str_replace(' ' ,'-' ,isset($products[1][0]) ? $products[0][0]: '#'  )).'.html'?>">
                                <?php if(!empty($products[1][1]))
                                    echo "<img class='img-responsive img-thumbnail' style='width: 95%;height: 150px;'  src='" . $block->getUrl() . "pub/media/catalog/product" . $products[1][1] . "'>";
                                else
                                    echo '<img class="img-responsive img-thumbnail" style="width: 95%;height: 150px;" src="'. $block->getUrl().'pub/static/version1512386094/frontend/Magento/luma/en_US/Magento_Catalog/images/product/placeholder/image.jpg">';
                                ?>
                            </a>                        </div>
                        <div class="clearfix"></div>
                    </div>
                    <div class="col2">
                        <a href="<?=$block->getUrl() . strtolower(str_replace(' ' ,'-' ,isset($products[2][0]) ? $products[2][0]: '#'  )).'.html'?>">
                            <?php if(!empty($products[2][1]))
                                echo "<img class='img-responsive img-thumbnail'style='width: 95%; height: 315px;'  src='" . $block->getUrl() . "pub/media/catalog/product" . $products[2][1] . "'>";
                            else
                                echo '<img class="img-responsive img-thumbnail" style="width: 95%; height: 315px;" src="'. $block->getUrl().'pub/static/version1512386094/frontend/Magento/luma/en_US/Magento_Catalog/images/product/placeholder/image.jpg">';
                            ?>
                        </a>
                    </div>
                    <div class="col3">
                        <div class="pull-left" style="width: 40%">
                            <img  class="img-responsive img-thumbnail"  style="width: 75%;height: 100px;"  src='<?= $block->getUrl() . "pub/media/shop/" . $shop['shop_logo']; ?>' alt="logo">
                        </div>
                        <div class="pull-left" style="width: 58%">
                            <h5><a  href="<?= $block->getUrl().'marketplace/shop/shop/profile/'. strtolower(str_replace(' ' ,'-' , $shop['shop_title'] ));?>"><?= $shop['shop_title'] ?></a></h5>
                            <h6><span><?= $products['total']?> Products  </span></h6>
                            <a class="btn btn-default" href="<?= $block->getUrl().'marketplace/shop/products/profile/'. strtolower(str_replace(' ' ,'-' , $shop['shop_title'] ));?>">View All</a>
                        </div>
                        <div class="clearfix"></div>
                    </div>
                </div>

            </div>

        <?php
            if($i > 2 )
                break;
            else
                $i++;

        endforeach;?>


    </div>
    <div class="row">
        <div class="text-center">

            <br><br>

            <h3><?=$label3; ?></h3>
            <a href="<?= $block->getUrl(). 'marketplace/sell/sellerList/' ?>" class="btn btn-default">View All</a>

        </div>


    </div>
</div>


<hr>
<!--about -->
<div class="am-about">
    <h1 class="text-center"><?= $label4 ?> </h1>
    <div class="row">
        <div class="col-md-12">
            <?= $about ?>
        </div>
    </div>
</div>

<hr>
<div class="text-center">
    <a href="<?= $block->getUrl(). 'customer/account/login/' ?>" class="btn btn-default">Open a Marketplace Shop</a>
</div>
<br>



