
<?php
$productName =str_replace(".html",'', str_replace($this->getUrl(),'' ,$this->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true])));
$productName = strtoupper(str_replace("-" , " " ,$productName) );
$shopView = $block->getShopView($productName);
if($shopView)
?>
<h4><b><a style="color: #000" href="<?php echo $this->getUrl(). "marketplace/shop/shop/profile/".strtolower(str_replace(' ' ,'-' , $shopView)) ; ?>"><?php echo  $shopView; ?> </a>
    </b></h4>







